----TẠO CƠ SỞ DỮ LIỆU--
--CREATE DATABASE CKWORLDCUP
--GO 

--USE CKWORLDCUP

--CREATE TABLE HLV 
--(
--    MAHLV CHAR(6),
--    TENHLV VARCHAR (40), 
--    QUOCTICH VARCHAR (20), 
--    NGSINH SMALLDATETIME,

--    CONSTRAINT PK_HLV PRIMARY KEY (MAHLV)
--)

--CREATE TABLE DOITUYEN 
--(
--    MADT CHAR(6),
--    QUOCGIA VARCHAR(20), 
--    MAHLV CHAR(6), 
--    CHAULUC VARCHAR(20), 
--    DIEM INT, 

--    CONSTRAINT PK_DOITUYEN PRIMARY KEY (MADT), 
--    CONSTRAINT FK_DOITUYEN FOREIGN KEY (MAHLV) REFERENCES HLV(MAHLV)
--)

--CREATE TABLE FINALWC 
--(
--    MAFWC CHAR(5), 
--    NUOCTC VARCHAR(10), 
--    NAM INT, 
--    NGBD SMALLDATETIME, 
--    TONGKP INT, 

--    CONSTRAINT PK_FINALWC PRIMARY KEY (MAFWC)
--)

--CREATE TABLE KETQUA 
--(
--    MAKQ CHAR(5), 
--    MADT CHAR(6),
--    MAFWC CHAR(5), 
--    TONGSOBT INT, 
--    THUHANG INT, 
--    HUYCHUONG VARCHAR(10)

--    CONSTRAINT PK_KETQUA PRIMARY KEY (MAKQ), 
--    CONSTRAINT FK_MADT FOREIGN KEY (MADT) REFERENCES DOITUYEN(MADT), 
--    CONSTRAINT FK_MAFWC FOREIGN KEY (MAFWC) REFERENCES FINALWC(MAFWC)
--)
-----------------------------------------------------------------------

--------------------------THÊM THÔNG TIN-------------------------------
--SET DATEFORMAT DMY 

----NHẬP THÔNG TIN HLV 
--INSERT INTO HLV(MAHLV, TENHLV, QUOCTICH, NGSINH) VALUES ('HLV001', 'Adenor Leonardo Bacchi', 'Brazil', '25/05/1961')
--INSERT INTO HLV(MAHLV, TENHLV, QUOCTICH, NGSINH) VALUES ('HLV002', 'Hansi Flick', 'Duc', '24/02/1965')
--INSERT INTO HLV(MAHLV, TENHLV, QUOCTICH, NGSINH) VALUES ('HLV003', 'Roberto Martinez', 'Tay Ban Nha', '13/07/1973')

----NHẬP THÔNG TIN ĐỘI TUYỂN
--INSERT INTO DOITUYEN(MADT, MAHLV, QUOCGIA, CHAULUC, DIEM) VALUES ('DT001', 'HLV001', 'Brazil', 'Chau My', '243')
--INSERT INTO DOITUYEN(MADT, MAHLV, QUOCGIA, CHAULUC, DIEM) VALUES ('DT002', 'HLV002', 'Duc', 'Chau Au', '222')
--INSERT INTO DOITUYEN(MADT, MAHLV, QUOCGIA, CHAULUC, DIEM) VALUES ('DT003', 'HLV003', 'Bi', 'Chau Au', '72')

----NHẬP THÔNG TIN FINALWC 
--INSERT INTO FINALWC(MAFWC, NUOCTC, NAM, NGBD, TONGKP) VALUES ('WC001', 'Qatar', '2022', '20/11/2022', '13')
--INSERT INTO FINALWC(MAFWC, NUOCTC, NAM, NGBD, TONGKP) VALUES ('WC002', 'Nga', '2018', '14/06/2018', '8')
--INSERT INTO FINALWC(MAFWC, NUOCTC, NAM, NGBD, TONGKP) VALUES ('WC003', 'Brazil', '2014', '12/06/2014', '7')

----NHẬP THÔNG TIN KETQUA 
--INSERT INTO KETQUA(MAKQ, MADT, MAFWC, TONGSOBT, THUHANG, HUYCHUONG) VALUES ('KQ001', 'DT001', 'WC001', '10', '1', 'Vang')
--INSERT INTO KETQUA(MAKQ, MADT, MAFWC, TONGSOBT, THUHANG, HUYCHUONG) VALUES ('KQ002', 'DT002', 'WC001', '9', '3', 'Bac')
--INSERT INTO KETQUA(MAKQ, MADT, MAFWC, TONGSOBT, THUHANG, HUYCHUONG) VALUES ('KQ003', 'DT003', 'WC001', '3', '10', NULL)
------------------------------------------------------------------------


--5.
SELECT HLV.MAHLV , HLV.TENHLV FROM HLV JOIN DOITUYEN ON HLV.MAHLV = DOITUYEN.MAHLV
WHERE HLV.QUOCTICH <> DOITUYEN.QUOCGIA

--6.


--7.
SELECT HLV.MAHLV , HLV.TENHLV FROM HLV JOIN DOITUYEN ON HLV.MAHLV = DOITUYEN.MAHLV
WHERE HLV.QUOCTICH = DOITUYEN.QUOCGIA AND HLV.MAHLV NOT IN (
																SELECT MAHLV FROM DOITUYEN
																	)