
CREATE DATABASE CUUHO
GO
USE CUUHO
GO
SET DATEFORMAT dmy 
GO


CREATE TABLE KHUVUC(
    MAKH VARCHAR(4) PRIMARY KEY,
    TENKV NVARCHAR(50),
    VITRI NVARCHAR(50),
    LOAIKV NVARCHAR(20)
)
GO
CREATE TABLE PHIEUCUUHO(
    SOPHIEU VARCHAR(4) PRIMARY KEY,
    MAKH VARCHAR(4) REFERENCES KHUVUC,
    LOAICH NVARCHAR(50),
    NGAYCH SMALLDATETIME
)
GO
CREATE TABLE DONGVAT(
    MADV VARCHAR(4) PRIMARY KEY,
    TENDV NVARCHAR(50),
    LOAIDV VARCHAR(4),
    SLCT INT,
    TLTB INT
)
GO
CREATE TABLE CTCH(
    SOPHIEU VARCHAR(4) REFERENCES PHIEUCUUHO,
    MADV VARCHAR(4) REFERENCES DONGVAT,
    SOLUONG INT,
    PRIMARY KEY (SOPHIEU,MADV)
)
GO

INSERT INTO KHUVUC (MAKH, TENKV, VITRI, LOAIKV) VALUES
('KV01', 'Khu vực A', 'Đông Bắc', 'Cạn'),
('KV02', 'Khu vực B', 'Tây Nam', 'Cạn'),
('KV03', 'Khu vực C', 'Đông Nam', 'Nước');

INSERT INTO PHIEUCUUHO (SOPHIEU, MAKH, LOAICH, NGAYCH) VALUES
('SP01', 'KV01', 'Tại chỗ', '12-07-2017'),
('SP02', 'KV03', 'Tại chỗ', '10-07-2017'),
('SP03', 'KV01', 'Chữa trị', '10-10-2023');
INSERT INTO DONGVAT (MADV, TENDV, LOAIDV, SLCT, TLTB) VALUES
('DV01', 'Bò biển', 'VU', 112, 120),
('DV02', 'Sao la', 'EN', 20, 25),
('DV03', 'Tê tê Gia va', 'EN', 17, 8),
('DV04', 'Khỉ đuôi lợn', 'VU', 330, 7);
INSERT INTO CTCH (SOPHIEU, MADV, SOLUONG) VALUES
('SP01', 'DV03', 9),
('SP01', 'DV02', 11),
('SP03', 'DV01', 9);


ALTER TABLE DONGVAT ADD CONSTRAINT CK_CHECK CHECK (LOAIDV <> 'EN' OR SLCT <= 20)
GO

SELECT SOPHIEU,LOAICH FROM PHIEUCUUHO JOIN KHUVUC ON PHIEUCUUHO.MAKH = KHUVUC.MAKH
WHERE KHUVUC.LOAIKV = 'Cạn' AND YEAR(NGAYCH) = 2017
ORDER BY NGAYCH ASC


SELECT MADV FROM DONGVAT
WHERE  MADV NOT  IN (
    SELECT MADV FROM CTCH
)

SELECT MADV FROM DONGVAT
WHERE  MADV   IN (
    SELECT MADV FROM CTCH
    WHERE SOLUONG >= ALL(
        SELECT SOLUONG FROM CTCH
    )
)
SELECT CTCH.SOPHIEU,NGAYCH FROM PHIEUCUUHO PCH 
                            JOIN CTCH ON CTCH.SOPHIEU = PCH.SOPHIEU
                            JOIN DONGVAT ON CTCH.MADV = DONGVAT.MADV
GROUP BY CTCH.SOPHIEU,NGAYCH  
HAVING SUM(DONGVAT.TLTB * CTCH.SOLUONG) > 300             
            
SELECT TENKV,VITRI FROM KHUVUC
WHERE MAKH IN (
    SELECT MAKH FROM PHIEUCUUHO
    WHERE SOPHIEU NOT IN (
        SELECT SOPHIEU FROM CTCH JOIN DONGVAT ON DONGVAT.MADV = CTCH.MADV
        WHERE LOAIDV <> 'EN'
    )
)
GO
--4.
/*
PHIEUCUUHO  +    -     +
KHUVUC      -    -     +
*/
CREATE TRIGGER TRG_UP ON PHIEUCUUHO
FOR INSERT,UPDATE
AS 
BEGIN
    IF EXISTS (
        SELECT * FROM inserted I JOIN KHUVUC ON KHUVUC.MAKH = I.MAKH
        WHERE KHUVUC.LOAIKV = 'Nước' AND I.LOAICH != 'Tại chỗ'
    )
    BEGIN
        PRINT 'LOI : INPUT KO HOP LE'
        ROLLBACK TRANSACTION
    END
    ELSE
    BEGIN
        PRINT 'THANH CONG'
    END
END
GO

CREATE TRIGGER TRG_UP ON KHUVUC
FOR INSERT,UPDATE
AS 
BEGIN
    IF EXISTS (
        SELECT * FROM inserted I JOIN PHIEUCUUHO ON PHIEUCUUHO.MAKH = I.MAKH
        WHERE I.LOAIKV = 'Nước' AND PHIEUCUUHO.LOAICH != 'Tại chỗ'
    )
    BEGIN
        PRINT 'LOI : INPUT KO HOP LE'
        ROLLBACK TRANSACTION
    END
    ELSE
    BEGIN
        PRINT 'THANH CONG'
    END
END
GO