--II.
--1.
UPDATE GIAOVIEN
SET HESO = HESO*1.2
WHERE MAGV IN 
	(
		SELECT TRGKHOA FROM KHOA	
	)
--2.


--3.
UPDATE  HOCVIEN
SET GHICHU = 'Cam thi'
WHERE MAHV IN	
(
	SELECT MAHV FROM KETQUATHI
	WHERE LANTHI = 3 AND DIEM < 5
)
--4.
UPDATE HOCVIEN SET XEPLOAI = CASE 
	WHEN DIEMTB >= 9 THEN 'XS'
	WHEN DIEMTB >= 8 THEN 'G'
	WHEN DIEMTB >= 6.5 THEN 'K'
	WHEN DIEMTB >= 5 THEN 'TB'
	ELSE 'Y'
END

--III.
--6.
SELECT TENMH FROM MONHOC AS MH
							INNER JOIN GIANGDAY AS GD ON MH.MAMH = GD.MAMH
							INNER JOIN GIAOVIEN AS GV ON GV.MAGV = GD.MAGV
WHERE GD.HOCKY = 1 AND GD.NAM = 2006 AND GV.HOTEN = 'Tran Tam Thanh'
GROUP BY TENMH

--7.
SELECT MH.MAMH,MH.TENMH FROM MONHOC AS MH
							INNER JOIN GIANGDAY AS GD ON MH.MAMH = GD.MAMH
							INNER JOIN GIAOVIEN AS GV ON GV.MAGV = GD.MAGV
WHERE GD.HOCKY = 1 AND GD.NAM = 2006 AND GV.MAGV IN 
													(
														SELECT MAGVCN FROM LOP
														WHERE MALOP = 'K11'
													)

GROUP BY MH.MAMH,MH.TENMH
--8.
SELECT HO,TEN  FROM HOCVIEN
WHERE MAHV IN 
(
	SELECT TRGLOP FROM LOP
	WHERE MALOP IN 
		(
			SELECT MALOP FROM GIANGDAY INNER JOIN GIAOVIEN ON GIANGDAY.MAGV = GIAOVIEN.MAGV
			WHERE GIAOVIEN.HOTEN = 'Nguyen To Lan' AND GIANGDAY.MAMH IN 
																(
																	SELECT MAMH FROM MONHOC
																	WHERE TENMH = 'Co so du lieu'
																)
		)
)

--9.
SELECT MH.MAMH,MH.TENMH FROM MONHOC AS MH
									
WHERE MH.MAMH IN 
(	
	SELECT MAMH_TRUOC FROM DIEUKIEN
	WHERE DIEUKIEN.MAMH IN (SELECT MAMH FROM MONHOC WHERE TENMH = 'Co so du lieu')
)

--10.
SELECT MH.MAMH,MH.TENMH FROM MONHOC AS MH
									
WHERE MH.MAMH IN 
(	
	SELECT MAMH FROM DIEUKIEN
	WHERE DIEUKIEN.MAMH_TRUOC IN (SELECT MAMH FROM MONHOC WHERE TENMH = 'Cau truc roi rac')
)

--11.
SELECT HOTEN FROM GIAOVIEN 
WHERE MAGV IN 
(
	SELECT MAGV FROM GIANGDAY
	WHERE HOCKY = 1 AND NAM = 2006 AND MALOP IN ('K11','K12') AND MAMH IN 
																	(
																		SELECT MAMH FROM MONHOC 
																		WHERE TENMH = 'Cau truc roi rac'
																	)
	GROUP BY MAGV
	HAVING COUNT(DISTINCT MALOP) = 2
)
